language: node_js
node_js:
  - "16"

cache: npm
  

install:
  - npm ci
# - npm install -g netlify-cli



script:
  - npm test
  



deploy:
  provider: script
  script: npm netlify-cli deploy --prod --auth $NETLIFY_TOKEN
  skip_cleanup: true
  on:
    branch: main