language: node_js
node_js:
  - "16"

cache: npm
  

install:
  - npm ci
# - npm install -g netlify-cli



script:
  - npm test
  



deploy:
  provider: netlify
  site: "c1db6dec-d9c9-4fe5-9f26-464706c38eb6"
  auth: $NETLIFY_TOKEN
  # script: npm netlify-cli deploy --prod --auth $NETLIFY_TOKEN
  # skip_cleanup: true
  # on:
  #   branch: main