language: node_js
node_js:
  - "16"

cache: npm
  

install:
  - npm ci
# - npm install -g netlify-cli



script:
  - npm test
  



deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: main