language: node_js
node_js:
  - "18.16.0"

cache: npm
  

install:
  - npm ci
# - npm install -g netlify-cli



script:
  - npm test
  - npm run dev



deploy:
  provider: script
  script: npm netlify-cli deploy --prod --auth $NETLIFY_TOKEN
  skip_cleanup: true
  on:
    branch: main