language: node_js
node_js:
  - "14"

exclude: 
  script: 
    - npm ci
    - npm test

env:
  global:
    - REPO_URL="https://github.com/pfloriansuero/react-PedroGifApp"

stages:
  - name: Desarrollo
  - name: QA
  - name: Producción
  - name: Deploy to GitHub Pages

jobs:
  include:
    - stage: Desarrollo
      script:
        - npm ci
        - git config --global credential.helper "!f() { echo username=pfloriansuero; echo password=$GITHUB_TOKEN; }; f"
        - git checkout Dev
        - git fetch origin main:main
        - git merge main
        - git push origin Dev
        - git config --global --unset credential.helper
        - npm run build

      notification:
        email:
          on_success: change
          on_failure: always

#     - stage: QA
#       script:
#         - npm eslint
#         - npm test
#         # Agrega más comandos de prueba de QA si es necesario
#         - git config --global credential.helper "!f() { echo username=pfloriansuero; echo password=$GITHUB_TOKEN; }; f"
#         - git checkout QA
#         - git fetch origin Dev:Dev
#         - git merge Dev
#         - git push origin QA
#         - git config --global --unset credential.helper

#     - stage: Producción
#       script:
#         - git config --global credential.helper "!f() { echo username=pfloriansuero; echo password=$GITHUB_TOKEN; }; f"
#         - git checkout Produccion
#         - git fetch origin QA:QA
#         - git merge QA
#         - git push origin Produccion
#         - git config --global --unset credential.helper
#         # - npm run test-file -- Login.test.js
#         # Agrega más comandos de prueba de producción si es necesario

#     - stage: Deploy to GitHub Pages
#       if: env(currentBuild.result) == 'SUCCESS'
#       script:
#         - npm install -g gh-pages
#         - npm run deploy

# after_script:
#   - git checkout main