language: node_js
node_js:
  - "14"

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npx jest

deploy:
  provider: script
  script: npx netlify-cli deploy --prod --auth $NETLIFY_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: main