pr:
 branches:
   include:
     - dev
   exclude:
     - qa
     - prod

pool: my-personal-computer

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Development
  jobs:
  - job: InstalarNode_InstalarCompilarApp_Deploy
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '18.x'
        checkLatest: true
      displayName: Instalar Node
    - script: |
        npm install
        npm test
      displayName: Instalar y pruebas unitarias
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'ricardoacosta15/gifapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.dev'
      displayName: To DockerHub

- stage: QA
  condition: succeeded()
  jobs:
  - deployment:
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                git checkout qa
                git merge dev
                git push origin qa
                npm run lint
              displayName: cambiar rama qa y linting
            - task: Docker@2
              inputs:
                containerRegistry: 'docker'
                repository: 'ricardoacosta15/gifapp'
                command: 'buildAndPush'
                Dockerfile: '**/Dockerfile.dev'
              displayName: To DockerHub

- stage: Production
  condition: succeeded()
  jobs:
  - deployment:
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              git checkout prod
              git merge qa
              git push origin prod
            displayName: cambiar rama prod
          - task: Docker@2
            inputs:
              containerRegistry: 'docker'
              repository: 'ricardoacosta15/gifapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile.dev'
            displayName: To DockerHub
          - script: |
                git checkout dev
            displayName: cambiar rama dev
